---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver_config:
      network:
      - ["private_network", {ip: "33.33.33.10"}]
    run_list:
      - recipe[apt]
    attributes:
      apt:
        compiletime: true

  - name: centos-6.5
    driver_config:
      network:
      - ["private_network", {ip: "33.33.33.11"}]

  - name: centos-6.6
    driver_config:
      network:
      - ["private_network", {ip: "33.33.33.12"}]

suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[tomcat-all::default]
    attributes:
      java:
        jdk_version: 7
      tomcat-all:
        ssl_enabled: true
